name: flutter_document_picker_example
description: Demonstrates how to use the flutter_document_picker plugin.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_document_picker:
    path: ../

flutter:
  uses-material-design: true


